# @package _global_

#### Model params #############################################################
# Naive forecast: repeats the last observed value for all horizon steps
model:
  name: naive
  hparams: {}

