# @package _global_

#### Model params #############################################################
model:
  name: stgnn
  hparams:
    hidden_size: 128
    emb_size: 32
    add_embedding_before: encoding
    time_layers: 2
    graph_layers: 2
    norm: none
    activation: elu
    noise_mode: lin
    time_skip_connect: true
