defaults:
  - _self_
  - dataset: temperature
  - model: tcn
  - lr_scheduler: multistep

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

experiment_name: peakweather_temperature
mlflow_tracking_uri: null

workers: 0
num_threads: 1

#### Training params ##########################################################
epochs: 200
patience: 20
batch_size: 32
grad_clip_val: 5

loss_fn: mae

sampling:
  mc_samples_train: 16
  mc_samples_eval: 11
  mc_samples_test: 100

scaler:
  method: Standard
  axis: global
  scale_target: true

optimizer:
  name: Adam
  hparams:
    lr: 0.001

load_model_path: null
