experiment_name: peakweather_temperature
mlflow_tracking_uri: null
seed: 1
workers: 4
epochs: 120
patience: 25
batch_size: 64
accumulate_grad_batches: 1
grad_clip_val: 5
loss_fn: ens
sampling:
  mc_samples_train: 16
  mc_samples_eval: 11
  mc_samples_test: 100
scaler:
  method: Standard
  axis: global
  scale_target: true
optimizer:
  name: Adam
  hparams:
    lr: 0.001
    weight_decay: 0.0001
dataset:
  name: Temperature
  hparams:
    root: ./PeakWeatherDataset
    target_channels:
    - temperature
    covariate_channels:
    - humidity
    - precipitation
    - pressure
    - sunshine
    freq: h
  splitting:
    first_val_ts:
    - 2024
    - 1
    - 1
    first_test_ts:
    - 2024
    - 4
    - 1
  connectivity:
    threshold: 0.5
    theta: null
    include_self: false
    knn: 12
    layout: edge_index
  covariates:
    year: true
    day: true
    mask: true
    u_mask: true
    v: true
  static_attributes:
  - latitude
  - longitude
  - station_height
  - dem
  - ASPECT_2000M_SIGRATIO1
  - ASPECT_10000M_SIGRATIO1
  - SLOPE_2000M_SIGRATIO1
  - SLOPE_10000M_SIGRATIO1
  - TPI_2000M
  - TPI_10000M
window: 72
horizon: 24
stride: 1
test_subsets:
- meteo_only
- all_with_temp
model:
  name: tcn
  hparams:
    hidden_size: 128
    num_layers: 3
    kernel_size: 3
    dropout: 0.2
lr_scheduler:
  name: MultiStepLR
  hparams:
    gamma: 0.3
    milestones:
    - 40
    - 60
    - 100
run:
  seed: 1
  dir: /home/filippo/GitHub/peakweather-wind-forecasting/logs/Temperature/tcn/2025-12-10/22-23-02
  name: 2025-12-10_22-23-02_1
